version: "3"
services:
  app:
    image: test-app-www
    container_name: test-app-www
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
      - mysql
    ports:
      - 8089:80
    volumes:
      - .:/var/www/html
    #command: bash -c "chown -R www-data:www-data /var/www/html"
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_CLIENT: predis

  scheduler:
    image: test-app-www
    container_name: test-app-scheduler
    depends_on:
      - app
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      CONTAINER_ROLE: scheduler
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_CLIENT: predis

  queue:
    image: test-app-www
    container_name: test-app-queue
    depends_on:
      - app
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_CLIENT: predis

  redis:
    container_name: test-app-redis
    image: redis:4-alpine
    ports:
      - 16379:6379
    volumes:
      - redis:/data

  mysql:
    container_name: test-app-mysql
    restart: "always"
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: testapp
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: test_app_user
      MYSQL_PASSWORD: secret

volumes:
  redis:
    driver: "local"

